# Generated by Django 4.2.3 on 2023-07-18 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_remove_articulos_actualizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='autor',
        ),
    ]
